---
#- name: install python-apt
#  apt: name="python-apt"

- name: install apticron
  apt: name="apticron"

- name: install config
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf owner=root group=root mode="644"
