---
- name: upgrade system
  apt: upgrade=full update_cache=yes

- name: purge packages
  apt: name="{{item}}" state=absent purge=yes
  with_items:
    - snmpd
    - avahi-daemon
    - nfs-kernel-server
    - nfs-common
    - portmap
    - rpcbind

- name: Autoremove unused packages
  command: apt-get -y autoremove
  register: autoremove_output
  changed_when: "'The following packages will be REMOVED' in autoremove_output.stdout"
