---
- name: install apache2
  apt: name=apache2 state=latest update_cache=yes

- name: enable ssl mod
  apache2_module: name=ssl state=present

- name: set default page + redirect http to https
  template: src="pheanex.de-http-https-redirect.conf" dest="/etc/apache2/sites-available/pheanex.de-http-https-redirect.conf"
  notify: restart_apache2

- name: remove default page
  file: name="/etc/apache2/sites-enabled/000-default.conf" state=absent
  notify: restart_apache2

- name: install eltsencrypt certbot package
  apt: name=python-certbot-apache state=latest

