---
- name: copy iptables script
  template: src=iptables.sh dest=/root/iptables.sh owner=root group=root mode="740"
  notify:
    - run iptables script
    - restart docker
    - restart fail2ban

- name: copy firewall script to network interaces
  template: src={{item}} dest=/etc/network/if-up.d/{{item}} owner=root group=root mode="755"
  with_items:
    - iptables.sh
    - docker
    - fail2ban

- name: copy firewall systemd unit
  template: src=firewall.service dest=/etc/systemd/system/firewall.service owner=root group=root mode="644"

- name: enable firewall startup script automatic on boot
  service: name=firewall.service enabled=yes
