---
- name: copy iptables script
  template: src=iptables dest=/root/iptables.sh owner=root group=root mode="740"
  notify:
    - run iptables script
    - restart docker
    - restart fail2ban

- name: copy firewall script to network interaces
  template: src=iptables dest=/etc/network/if-up.d/iptables owner=root group=root mode="755"
