#!/bin/bash
journalctl --since yesterday -p4 | tail -n+2 | awk '{for(i=5;i<NF;i++){if(i==5 && $i ~/^sshd\[/){printf "sshd "}else if(i+1==NF){print $i}else{printf "%s ",$i}}}' | sort | uniq -c | sort -nr | column | mail -s "Rodin logs from $(date +"%d.%m.%Y")" root@pheanex.de
