vetinari_ssh_fingerprint: "vetinari.nonymus.de ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBECSX3Voi9aQiOagpwHKw4cDZZsZyO5avWRhktezfwXF/Hr1QbqG+66s3cPm4TSh0zTbIEX/s9rUqsm39gYgoFU="
